### ISSUE TITLE
Publication pending (?)

### ISSUE THREAD

**Issue by eduardsmirnov** [anskaffelser/eforms-sdk-nor#19]
Just to check with you if publication is pending due to TED or Doffin. Could you answer?

Notices are:
70dae2db-28db-4cab-baa2-d9fb00db9688-01 (EU 1, submitted 2023-09-07T18:53:13+03:00, visible in Search API)
4c0ea1fe-b9b4-42b0-bd52-6e1120fe8a08-01 (EU 16, submitted 2023-09-08T14:32:16+03:00, not visible in Search API)
f76d61af-159a-4ff0-9e40-da6ad32f617b-01 (national N16, submitted 2023-09-08T18:05:09+03:00, not visible in Search API)

**Comment by haroonalam16** [comment]
Hello,

National N16 f76d61af-159a-4ff0-9e40-da6ad32f617b-01 is PUBLISHED. Can you check now if it is visible to Search API?
All National notices (N16, N30) which are ready for publishing being prepared for publishing at 08:50 (status = PUBLISHING) and at 09:00 it published with status = PUBLISHED.

With other notices (EU 1 & EU 16) you mentioned, we are checking it. We will come back to you as soon as possible. Thanks.

**Comment by eduardsmirnov** [comment]
N16 is published, right, a status received correctly.

**Comment by sandrawiborg** [comment]
Hi Eduard. For your information: The national notices in this issue are solved. For the ones publishing on TED we are investigating this issue and will keep you informed. Reported in Jira: [DOF-1387](https://dfo-no.atlassian.net/browse/DOF-1387)

**Comment by sandrawiborg** [comment]
We are working on this issue now. We hope we are close to find a solution and will keep you informed.

**Comment by haroonalam16** [comment]
Hello,

On Friday we have rolled out the fix and issue with EU notices (1, 16 etc) which were taking so long time to sent to TED is solved now.

EU notices will be sent to TED within 5 minutes once we receive them. Sender will receive email directly from TED in both cases either Notices is SUBMITTED or VALIDATION_FAILED.

Once TED PUBLISH the EU notice, we also publish the EU notice to Doffin, it could take 1 minute to 2 hours to Publish to Doffin because we are polling to TED every 2 hours to check the status.

**Comment by sandrawiborg** [comment]
Hi @eduardsmirnov 
I close this issue, as the case is solved. If you experience this type of error again, please let us know.
