### ISSUE TITLE
Inconsistent search API

### ISSUE THREAD

**Issue by 577854** [anskaffelser/eforms-sdk-nor#35]
Hello,

My program has been getting the new eForms tenders from the new API for a few days now. I am also still requesting daily tenders from the old Doffin API (https://dpsv3.doffin.no/api). 

It seems to me that the new API (https://api.doffin.no/public/v2/search) does not give the same tenders as the old API. An example would be: 

The old API gave me 30 tenders from yesterday (30.10.2023) while the new API gives me 0 tenders from yesterday. I look into some of these tenders and see that they do not show up in the new Doffin search website so they only show up in the classic Doffin url.

My program also makes requests at 08:00 in the morning and it seems like i usually get 0 tenders from the day before. However if i make the request again at some point after 10 or 10:30 i get a number of thenders.

I have also noticed that the amount of tenders from some of the days last week, have more tenders than they used to have. An example would be when my program got tenders on the 26.10.2023 and searched for all tenders from yesterday (25.10.2023), i got 15 tenders. If i search for tenders published on the 25.10.2023 today, i get 65 tenders.

Under you can see an example of the times I made the same request and see that the responses are very different:

Request time,             Request and                                                                  Response
----------------------------------------------------------------------------------------------------------
2023-10-26, 07:00:     request all tenders from (2023-10-25) ->     response: 0 tenders.
2023-10-26, 10:30:     request all tenders from (2023-10-25) ->     response: 15 tenders
2023-10-31, 11:20:     request     all     tenders     from      (2023-10-25) ->     response: 65 tenders

My questions are:
- Why are more tenders showing up for spesific days later on? Shouldn't published tenders from yesterday allways be the same after that day has passed? 
- Is there a spesific time of the day that my program should request tenders from the day before?
- Is the old API supposed to show the same ammount of tenders from a given day as the new API on the same given day?
- When will the old API be discontinued/stopped?

**Comment by haroonalam16** [comment]
Hello,
Yes, you are right Search results can be inconsistent which have reason. At the moment two systems for submitting Notices are running, one "Classic/Old" with which one can submit old format Notices, while other one is "New/eForms" with which one can send new eForm format Notices. 

`Why are more tenders showing up for spesific days later on? Shouldn't published tenders from yesterday allways be the same after that day has passed?`

Notices which are published on Classic system, we fetch next moring and convert it to eform format and then upload to New system. Fetching the classic Notices and uploading is semi-automatic process, and last step is manual and we usually do it after 09:00.
If old Doffin API give you 30 notices for the day 31st October and on New System if 15 eform Notices published on 31st October. so when you try you query:
08:00: old Doffin API (https://dpsv3.doffin.no/api) => 30
08:00:  new API (https://api.doffin.no/public/v2/search) => 15

if we be able to fetch and upload the classic/old Notices to New system at 10:00. and if you do the same query again around 10:30:
 
10:30: old Doffin API (https://dpsv3.doffin.no/api) => 30
10:30:  new API (https://api.doffin.no/public/v2/search) => 45

Note: if everything goes well with converting and uploading old Notices to new system then we will get 100% correct amount, but if due to some reason one or more notices are not imported to new system then count can vary.

`is there a spesific time of the day that my program should request tenders from the day before?`
It is difficult to say a specific time of the day because process is semi-automatic, but 11:00 is bit safe to check.

`Is the old API supposed to show the same ammount of tenders from a given day as the new API on the same given day?`
As I explained above, old API will show result for Old format Notices, while new will show the aggregate results for both new and old Format Notices.

`When will the old API be discontinued/stopped?`
@kjorlaug @sandrawiborg Can you please check this.

Hoping above explanation will help you to understand the difference and adjust your query program. Please don't hesitate to contact if anything is unclear :)

Haroon

**Comment by kjorlaug** [comment]
The old API will only be available for the rest of the year, after that everything will be on eForms. The important thing here is as @haroonalam16 is saying - all new notifications using eForms are only available through the new API. The delay in the transfer between platforms is the main reason we have advised to add 48-hours to deadlines when using the old format.
