### ISSUE TITLE
Notice submitted on November, 24th still "in progress" a week later

### ISSUE THREAD

**Issue by jlouvrier** [anskaffelser/eforms-sdk-nor#51]
Hi!
Can you explain to me why the following notice, submitted a week ago is still "In progress": fe88efc9-8021-4725-9c2c-121c70b0c501

**Comment by sandrawiborg** [comment]
Hi @jlouvrier 
Unfortunately, we haven't been able to look into this matter today because of a lack of capacity. Therefore, I request your understanding that this will take some time. We'll give you feedback on Monday when we've had time to investigate the matter. 

I wish you a good weekend.

Best regards, 
Sandra

**Comment by kjorlaug** [comment]
Thanks for the heads up @jlouvrier. We have located and restarted the prosess. The notice is now submitted to ted and should be published some time next week.

We will investigate why it stopped up, but for now this looks like a once off problem.
