### ISSUE TITLE
Validator support for v1.10

### ISSUE THREAD

**Issue by aso-ivalua** [anskaffelser/eforms-sdk-nor#73]
Hello, I would like to know if you plan on adding support for v1.10 on the online validator: https://anskaffelser.dev/service/validator/ .
We are planning on upgrading from v1.7 to v1.10, and having some quick feedback from the validator would be very helpful.
Thank you

**Comment by kjorlaug** [comment]
Sorry for a bit delay in answering. We have decided to skip 1.10 and go straight for 1.11 due to needed new NUTS codes missing in 1.10. We expect OPs 1.11 to be released in the near future, and will follow with a Norwegian SDK shortly after that. This release will be available in the validator then.
