### ISSUE TITLE
[dev] api portal site unavailable

### ISSUE THREAD

**Issue by ewlidd** [anskaffelser/eforms-sdk-nor#78]
The URL is unavailable: https://dof-notices-dev-api.portal.azure-api.net
It returns 503.
My colleagues are unable to create dev subscription IDs for testing nor view the API specs.

**Comment by haroonalam16** [comment]
Hello,
You can find all relevant links and information on the following page
https://github.com/anskaffelser/eforms-sdk-nor (readme scetion) 

for example in order to create subscription  doe DEV you can use following link: https://dof-notices-dev-api.developer.azure-api.net

Please don't hesitate to get back if problem persist. 

Thanks & Regards,
Haroon
