### ISSUE TITLE
CAN passes DOFFIN's validation but is later rejected by TED

### ISSUE THREAD

**Issue by jlouvrier** [anskaffelser/eforms-sdk-nor#81]
Hi! I would be grateful if you would investigate this case: b5fd434c-2306-4f43-ab78-f2ef4e9c5350-04

To me, it looks like an issue on your end when replacing the Norwegian custom award criterion type with the code list value expected in TED.

**Comment by kjorlaug** [comment]
This root case is the same as in issue #74 - the quality-nor-env-none code is used as quality with weight, whereas the intent was for this code only to be used with weight 0 (as in the veileder). The current logic on our side is to remove the whole criteria.

A quickfix is to use quality instead of quality-nor-env-none, with the option of splitting it in two (one for the assesement of quality, and one weighted 0 with the rationale for not putting weight on environment).
